[package]
name = "rustbench"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = { version = "2.0", features = ["full"] }

[lib]
proc-macro = true

[[example]]
name = "bench"
path = "./example/bench.rs"
